import type {
  AirPollutionDetails,
  SharedEvent,
} from '../types/events'

const details = {
  pollutant: 'PM2.5',
  station: {
    id: 'dev-haifa-neve-shaanan',
    name: 'Haifa – Neve Sha’anan',
    provider: 'israel_ministry_environment_air_monitoring',
    channel_id: 'pm25-preview-channel',
  },
  measured_value: 47.2,
  unit: 'µg/m³',
  observation_timestamp: '2026-09-15T06:35:00Z',
  historical_baseline: {
    p95: 31.8,
    month: 9,
    hour: 8,
    sample_count: 842,
    distinct_days: 126,
    distinct_years: 4,
    baseline_family: 'five_minute_observation',
    baseline_version_id: 'dev-preview-baseline-v1',
    baseline_content_sha256: 'development-preview-not-a-real-baseline-version',
  },
  ministry_aqi: {
    station_index: 82,
    station_category: 'Moderate',
    category_color: '#f59e0b',
    pollutant_sub_index: 78,
    driving_pollutant: 'PM2.5',
    averaged_concentration: 43.6,
    averaging_period_minutes: 30,
    provider_timestamp: '2026-09-15T06:30:00Z',
    preliminary: true,
    source: 'Israeli Ministry of Environmental Protection',
  },
  wind: {
    provider: 'Israel Meteorological Service',
    source_type: 'station_observation',
    provider_location_name: 'Haifa Technion',
    observed_or_valid_at: '2026-09-15T06:30:00Z',
    wind_from_direction_deg: 275,
    wind_speed_mps: 4.8,
    gust_from_direction_deg: 282,
    gust_speed_mps: 7.1,
    direction_stddev_deg: 12,
    reference: 'DEVELOPMENT PREVIEW – no live provider request',
    evidence_id: 'dev-preview-wind-evidence',
  },
  transport: {
    // Geometry is intentionally supplied as if serialized by the backend. The
    // preview layer renders these coordinates without deriving or changing it.
    corridor: {
      type: 'Polygon',
      coordinates: [[
        [35.015, 32.790],
        [35.102, 32.817],
        [35.090, 32.854],
        [35.053, 32.840],
        [35.015, 32.790],
      ]],
    },
    centerline: {
      type: 'LineString',
      coordinates: [
        [35.015, 32.790],
        [35.091, 32.835],
      ],
    },
    downwind_to_direction_deg: 62,
    corridor_method: 'direction_variability_screening',
    corridor_half_angle_deg: 18,
    max_screening_distance_m: 9200,
    direction_stddev_deg: 12,
    geometry_reference: 'dev-preview-corridor-geometry',
  },
  relevant_settlements: [
    {
      id: 'dev-nesher',
      name: 'Nesher',
      longitude: 35.049,
      latitude: 32.766,
      inside_transport_corridor: true,
      rank: 1,
      potential_downwind_relevance: 'higher',
      distance_m: 4300,
      transport_time: {
        status: 'estimated',
        seconds: 896,
        method: 'constant_wind_kinematic_screening',
        assumptions: [
          'Constant surface wind is used only as a kinematic screening proxy.',
          'The estimate does not confirm pollutant transport or exposure.',
        ],
      },
    },
    {
      id: 'dev-yagur',
      name: 'Yagur',
      longitude: 35.076,
      latitude: 32.742,
      inside_transport_corridor: true,
      rank: 2,
      potential_downwind_relevance: 'moderate',
      distance_m: 7100,
      transport_time: {
        status: 'estimated',
        seconds: 1479,
        method: 'constant_wind_kinematic_screening',
        assumptions: [
          'Constant surface wind is used only as a kinematic screening proxy.',
          'The estimate does not confirm pollutant transport or exposure.',
        ],
      },
    },
  ],
  population_within_screening_corridor: {
    total_relevant_population: 18420,
    intersected_cell_count: 37,
    queried_at: '2026-09-15T06:40:00Z',
    geometry_reference: 'dev-preview-corridor-geometry',
    dataset_reference_year: null,
  },
  recommendations: [
    {
      recommendation: 'Continue enhanced monitoring and verify subsequent station observations.',
      rationale: 'The measurement is historically unusual and should be checked against subsequent validated observations.',
      responsible_authority_type: 'environmental_protection_authority',
      resource_type: 'air_quality_monitoring',
      timeframe: 'ongoing',
      priority: 'monitoring',
      spatial_relevance: 'The possible corridor provides screening context only and does not confirm transport.',
    },
    {
      recommendation: 'Prepare a factual public-information update if the source-native category warrants it.',
      rationale: 'Public communication should rely on Ministry-native evidence and clearly state uncertainty.',
      responsible_authority_type: 'local_authority',
      resource_type: 'public_information',
      timeframe: 'within_1_hour',
      priority: 'routine',
      spatial_relevance: null,
    },
  ],
  verified_references: [
    {
      id: 'dev-preview-protocol-reference',
      document_title: 'Development preview reference – not live guidance',
      source_url: null,
      quoted_text: 'This preview text exists only to exercise verified-reference presentation.',
      supports: 'Development-only visual inspection of reference rendering.',
      verified: true,
    },
  ],
  unavailable_components: [
    {
      component: 'Trend ML',
      reason: 'Not yet implemented; no trend is inferred from the preview measurement.',
    },
  ],
  limitations: [
    'DEVELOPMENT PREVIEW / NOT LIVE. All displayed values are representative fixture data.',
    'p95 indicates historical unusualness and is not a health threshold.',
    'The corridor is possible transport screening, not a confirmed plume or exposure area.',
    'Population is geographically intersecting the screening corridor, not affected or exposed population.',
  ],
  trend: null,
} satisfies AirPollutionDetails

export const airPollutionPreviewEvent = {
  id: 'development-preview-air-pollution-haifa',
  type: 'air_pollution',
  classification: 'advisory',
  title: 'DEVELOPMENT PREVIEW / NOT LIVE – PM2.5 near Haifa',
  description: 'Representative Air Pollution event for frontend visual inspection only.',
  latitude: 32.790,
  longitude: 35.015,
  observed_at: details.observation_timestamp,
  analysis_status: 'partial',
  planning_status: 'success',
  details,
} satisfies SharedEvent
